
services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=vibe-bot
      - MARIADB_USER=vibe-bot
      - MARIADB_PASSWORD=foobar
    healthcheck:
      test: mariadb -uvibe-bot -pfoobar vibe-bot -e "select 1"
      interval: 3s
      timeout: 60s
      retries: 5
      start_period: 10s
      start_interval: 3s
    ports:
      - "3306:3306"
  bot:
    build: .
    environment:
      - DB_HOST=mariadb
      - DB_NAME=vibe-bot
      - DB_USER=vibe-bot
      - DB_PASSWORD=foobar
      - TZ=Europe/Berlin
      - GAME_START_TIME=13:37:00.000
      - SERGEANT_ROLE_ID=${SERGEANT_ROLE_ID}
      - COMMANDER_ROLE_ID=${COMMANDER_ROLE_ID}
      - GENERAL_ROLE_ID=${GENERAL_ROLE_ID}
      - ANNOUNCEMENT_CHANNEL_ID=${ANNOUNCEMENT_CHANNEL_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
        mariadb:
            condition: service_healthy