name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_discord_bot
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up test environment
        run: |
          echo "Setting up test environment variables"
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_USER=test_user" >> $GITHUB_ENV
          echo "DB_PASSWORD=test_password" >> $GITHUB_ENV
          echo "DB_NAME=test_discord_bot" >> $GITHUB_ENV
          echo "GAME_START_TIME=13:37:00.000" >> $GITHUB_ENV

      - name: Wait for database
        run: |
          echo "Waiting for MariaDB to be ready..."
          sleep 10

      - name: Run all tests
        run: |
          python -m unittest discover tests -v

      - name: Run critical game logic tests
        run: |
          echo "Running critical game logic tests..."
          python -m unittest tests.test_game_1337_logic.TestGame1337Logic.test_apply_winner_selection_rules_regular_closer -v
          python -m unittest tests.test_game_1337_logic.TestGame1337Logic.test_apply_winner_selection_rules_early_bird_closer_with_penalty -v
          python -m unittest tests.test_game_1337_logic.TestGame1337Logic.test_get_milliseconds_since_midnight -v
          python -m unittest tests.test_game_1337_logic.TestGame1337Logic.test_apply_winner_selection_rules_millisecond_precision -v

      - name: Test syntax check
        run: |
          echo "Checking syntax of all Python files..."
          python -m py_compile main.py
          python -m py_compile game/game_1337_logic.py
          python -m py_compile commands/*.py
          python -m py_compile tests/*.py
          echo "All Python files have valid syntax!"

      - name: Test import check
        run: |
          echo "Testing imports..."
          python -c "import commands.rules_1337_command; print('Rules command imports successfully')"
          python -c "import game.game_1337_logic; print('Game logic imports successfully')"
          python -c "import database; print('Database imports successfully')"
          python -c "import config; print('Config imports successfully')" 